### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by jcpaik** [jcpaik/conway-soifer-triangle#1]
- [x] Make URLs displayed in references
  - Seems helpful: https://tex.stackexchange.com/questions/117745/bibtex-display-url-in-reference
- [x] Add figures
  - [x] Graphs of $\nabla_a, \Delta_a$ and $x \mapsto \{ax + c\}$
- [x] Make short titles so that the title fits in page

**Comment by seewoo5** [comment]
- [ ] $\tilde{a}$ and {a} are essentially the same thing - unify them?

**Comment by jcpaik** [comment]
> * [ ]  a~ and {a} are essentially the same thing - unify them?

Write like the following: $f(z + \mathbb{Z}) = \lbrace z \rbrace$

**Comment by seewoo5** [comment]
Short title: cover an triangle -> cover a triangle?
