### ISSUE TITLE
Add figure

### ISSUE THREAD

**Issue by jcpaik** [jcpaik/conway-soifer-triangle#9]
https://jamboard.google.com/d/1fG2w_KJVAyf3rkN2G-aKSazDM35s1R5ONxS0AjUdygE

**Comment by jcpaik** [comment]
@seewoo5 지금 Figure 4의 그래프에 대응하는 실제 삼각형 모양 + 첫번째 theorem 맨 첫문단에 언급한 triangular grid 그림. 작업해주면 진짜 고마울듯 ㄱㅅㄱㅅ

**Comment by jcpaik** [comment]
두번째 페이지에는 지금 n^2+2, n^2+3 증명 합치면서 넣을 그래프 스케치해놓음. 이건 너가 해놓은 그래프 수정해서 내가 작업하겠음.

**Comment by seewoo5** [comment]
> @seewoo5 지금 Figure 4의 그래프에 대응하는 실제 삼각형 모양 + 첫번째 theorem 맨 첫문단에 언급한 triangular grid 그림. 작업해주면 진짜 고마울듯 ㄱㅅㄱㅅ

'지금' figure 4가 어떤 브랜치 기준이에요?
